name = "http-proxy"
main = "src/index.js"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# Cấu hình cho production
[env.production]
name = "http-proxy-prod"

# Cấu hình cho development  
[env.development]
name = "http-proxy-dev"

# Variables (optional)
[vars]
ENVIRONMENT = "production"

[observability.logs]
enabled = true

# Triggers - khi nào worker sẽ chạy
[[triggers]]
pattern = "*/*"
zone_name = "hoaithuong.id.vn"  # Thay bằng domain của bạn (optional)

# KV Storage (nếu cần)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# Durable Objects (nếu cần)
# [[durable_objects.bindings]]
# name = "COUNTER"
# class_name = "Counter"